# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-05 22:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cghs_financial', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='tags',
            field=models.ManyToManyField(related_name='expenses', to='cghs_financial.Tag'),
        ),
    ]
